from dashboard.figures.distribution import DistributionFigure
from dashboard.figures.activity import ActivityFigure
from dashboard.figures.selection import SelectionFigure
from dashboard.figures.evaluation import EvaluationFigure
from dashboard.figures.communication import CommunicationEnergyFigure
